routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Frontend\PageController@landing')->name('landing');
Route::get('/about', 'Frontend\PageController@pageAbout')->name('page.about');
// Route::get('/smart-rec', 'Frontend\SmartController@index')->name('smart-rec.index');
// //Route::post('/smart-rec', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::get('/smart-rec/process', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::post('/package/detail', 'Frontend\SmartController@detailPackage')->name('pg.detail');
Route::get('/checkout/{id}', 'Frontend\PageController@checkout')->name('page.checkout')->middleware('auth');
Route::post('/checkout', 'Frontend\PageController@checkoutStore')->name('page.checkout.store')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/account/profile', 'ProfileController@show')->name('profile.show');
Route::put('/account/profile', 'ProfileController@update')->name('profile.update');
Route::put('/account/profile/member', 'ProfileController@updateMember')->name('profile.update.member');

Route::group(['prefix' => 'main', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('user', 'Backend\UserController@index' )->name('user.index');
    Route::post('user', 'Backend\UserController@store' )->name('user.store');
    Route::get('user/create', 'Backend\UserController@create' )->name('user.create');
    Route::get('user/{id}/edit', 'Backend\UserController@edit' )->name('user.edit');
    Route::put('user/{id}/update', 'Backend\UserController@update' )->name('user.update');
    Route::delete('user/{id}', 'Backend\UserController@destroy' )->name('user.destroy');

    Route::resource('ticket', 'Backend\TicketController');
    Route::resource('order', 'Backend\OrderController');
    Route::resource('payment', 'Backend\PaymentController');
});


Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'role:user']], function () {
    Route::get('/my-order/{id}/cancel', 'Frontend\MyOrderController@cancel')->name('my-order.cancel');
    Route::resource('my-order', 'Frontend\MyOrderController');
});

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $appends = ['display_status'];

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->status;

        switch ($status) {
            case '100':
                $result = 'Aktif';
                break;
            case '10':
                $result = 'Tidak Aktif';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Order;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $orders = Order::with('user', 'ticket');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $orders->whereStatus($request->status);
                }
            }

            $orders = $orders->select('orders.*');

            return Datatables::of($orders)
                ->addIndexColumn()
                ->addColumn('action', function ($order) {
                    return view('partials._action', [
                        'model'           => $order,
                        // 'form_url'        => route('order.destroy', $order->id),
                        'edit_url'        => route('order.edit', $order->id),
                        'show_url'        => route('order.show', $order->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.orders.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);

        return view('backend.orders.show')->with(compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);

        return view('backend.orders.edit')->with(compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'status' => 'required|integer',
        ]);

        $order = Order::find($id);
        $order->status = $request->status;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil mengubah order"
        ]);

        return redirect()->route('order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/PaymentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Payment;
use App\Order;


class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $payments = Payment::with('user', 'order');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $payments->whereStatus($request->status);
                }
            }

            $payments = $payments->select('payments.*');

            return Datatables::of($payments)
                ->addIndexColumn()
                ->addColumn('action', function ($payment) {
                    return view('partials._action', [
                        'model'           => $payment,
                        // 'form_url'        => route('payment.destroy', $payment->id),
                        // 'edit_url'        => route('payment.edit', $payment->id),
                        'verif_url'        => route('payment.edit', $payment->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.payments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $payment = Payment::find($id);

        return view('backend.payments.edit')->with(compact('payment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'is_paid' => 'required|integer',
        ]);

        $payment = Payment::find($id);
        $payment->is_paid = $request->is_paid;
        $payment->save();

        $order = Order::find($payment->order_id);
        $order->status = 200;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil melakukan verifikasi"
        ]);

        return redirect()->route('payment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/TicketController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Order;
use App\Ticket;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $tickets = Ticket::query();

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $tickets->whereStatus($request->status);
                }
            }

            $tickets = $tickets->select('tickets.*');

            return Datatables::of($tickets)
                ->addIndexColumn()
                ->addColumn('action', function ($ticket) {
                    return view('partials._action', [
                        'model'           => $ticket,
                        'form_url'        => route('ticket.destroy', $ticket->id),
                        'edit_url'        => route('ticket.edit', $ticket->id),
                        'show_url'        => route('ticket.show', $ticket->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.tickets.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.tickets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'string',
            'event_date' => 'required|date',
            'price' => 'required|integer',
            'image' => 'required|image',
            'video_url' => 'string',
        ]);

        $ticket = new Ticket();
        $ticket->name = $request->name;
        $ticket->description = $request->description;
        $ticket->event_date = $request->event_date;
        $ticket->price = $request->price;
        $ticket->video_url = $request->video_url;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
           
            $ticket->image = $filename;
        }
        $ticket->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Tiket dengtan nama $ticket->name berhasil dibuat"
        ]);

        return redirect()->route('ticket.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket = Ticket::find($id);

        return view('backend.tickets.show')->with(compact('ticket'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::find($id);

        return view('backend.tickets.edit')->with(compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'string',
            'event_date' => 'required|date',
            'price' => 'required|integer',
            'image' => 'image',
            'video_url' => 'string',
        ]);

        $ticket = Ticket::find($id);
        $ticket->name = $request->name;
        $ticket->description = $request->description;
        $ticket->event_date = $request->event_date;
        $ticket->price = $request->price;
        $ticket->video_url = $request->video_url;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);

            // delete old image
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets'
                . DIRECTORY_SEPARATOR . $ticket->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
           
            $ticket->image = $filename;
        }
        $ticket->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Tiket dengtan nama $ticket->name berhasil diubah"
        ]);

        return redirect()->route('ticket.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ticket = Ticket::find($id);

        $check = Order::where('ticket_id', $id)->count();

        if ($check > 0) {
            Session::flash("flash_notification", [
                "level" => "warning",
                "message" => "Tidak dapat menghapus tiket ini, karena tiket ini sudah memiliki order. Alternatif anda dapat menonaktifkannya"
            ]);
            return redirect()->back();
        }

        if ($ticket->image) {
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets'
                . DIRECTORY_SEPARATOR . $ticket->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        $ticket->delete();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil menghapus data"
        ]);

        return redirect()->route('ticket.index');
    }
}

resources/views/backend/tickets/create.blade.php
@extends('layouts.main')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Tambah Tiket</h1>
    </div>

    <form method="POST" action="{{ route('ticket.store') }}" enctype="multipart/form-data">
      <div class="row">
        <div class="col-lg-8">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Informasi Tiket</h6>
            </div>
            <div class="card-body">
              {{ csrf_field() }}

              <div class="row">
                <div class="form-group col-12 {{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="name">Nama Tiket</label>
                  <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ old('name') }}">
                  @if ($errors->has('name'))
                    <div class="invalid-feedback">
                      {{ $errors->first('name') }}
                    </div>
                  @endif
                </div>
                <div class="form-group col-12 {{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="d-block">Deskripsi</label>
                  <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" value="{{ old('description') }}">
                  @if ($errors->has('description'))
                    <div class="invalid-feedback">
                      <strong>{{ $errors->first('description') }}</strong>
                    </div>
                  @endif
                </div>
              </div>

              <div class="row">
                <div class="form-group col-12 {{ $errors->has('price') ? ' has-error' : '' }}">
                  <label for="price">Harga Tiket</label>
                  <input id="price" type="text" class="form-control @if ($errors->has('price')) is-invalid @endif" name="price" tabindex="1" value="{{ old('price') }}">
                  @if ($errors->has('price'))
                    <div class="invalid-feedback">
                      {{ $errors->first('price') }}
                    </div>
                  @endif
                </div>

                <div class="form-group col-12 {{ $errors->has('event_date') ? ' has-error' : '' }}">
                  <label for="event_date">Tanggal Tiket</label>
                  <input id="event_date" type="date" class="form-control @if ($errors->has('event_date')) is-invalid @endif" name="event_date" tabindex="1" value="{{ old('event_date') }}">
                  @if ($errors->has('event_date'))
                    <div class="invalid-feedback">
                      {{ $errors->first('event_date') }}
                    </div>
                  @endif
                </div>
              </div>

              <div class="form-group {{ $errors->has('video_url') ? ' has-error' : '' }}">
                <label for="video_url" class="d-block">Youtube Video Url</label>
                <input id="video_url" type="text" class="form-control @if ($errors->has('video_url')) is-invalid @endif" name="video_url" value="{{ old('video_url') }}">
                @if ($errors->has('video_url'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('video_url') }}</strong>
                  </div>
                @endif
              </div>              

              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                  Simpan
                </button>
              </div>
              
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Image / Marker</h6>
            </div>
            <div class="card-body">
              <div class="form-group">
                <div class="text-center">
                  <img src="{{ asset('assets/stisla/img/news/img02.jpg') }}" class="rounded" id="image-prev" width="200" alt="avatar">
                </div>
              </div>
              <div class="form-group custom-file mb-3 {{ $errors->has('image') ? ' has-error' : '' }}">
                <input id="image" type="file" class="custom-file-input @if ($errors->has('image')) is-invalid @endif" name="image" />
                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                @if ($errors->has('image'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('image') }}</strong>
                  </div>
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })

    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#image-prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
      }
    }

    $("#image").change(function() {
      readURL(this);
    });
  </script>
@endsection

resources/views/backend/tickets/edit.blade.php
@extends('layouts.main')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Edit Tiket</h1>
    </div>

    <form method="POST" action="{{ route('ticket.update', $ticket->id) }}" enctype="multipart/form-data">
      <div class="row">
        <div class="col-lg-8">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Informasi Tiket</h6>
            </div>
            <div class="card-body">
              {{ csrf_field() }}
              @method('PUT')

              <div class="row">
                <div class="form-group col-12 {{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="name">Nama Tiket</label>
                  <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ $ticket->name }}">
                  @if ($errors->has('name'))
                    <div class="invalid-feedback">
                      {{ $errors->first('name') }}
                    </div>
                  @endif
                </div>
                <div class="form-group col-12 {{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="d-block">Deskripsi</label>
                  <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" value="{{ $ticket->description }}">
                  @if ($errors->has('description'))
                    <div class="invalid-feedback">
                      <strong>{{ $errors->first('description') }}</strong>
                    </div>
                  @endif
                </div>
              </div>

              <div class="row">
                <div class="form-group col-12 {{ $errors->has('price') ? ' has-error' : '' }}">
                  <label for="price">Harga Tiket</label>
                  <input id="price" type="text" class="form-control @if ($errors->has('price')) is-invalid @endif" name="price" tabindex="1" value="{{ $ticket->price }}">
                  @if ($errors->has('price'))
                    <div class="invalid-feedback">
                      {{ $errors->first('price') }}
                    </div>
                  @endif
                </div>

                <div class="form-group col-12 {{ $errors->has('event_date') ? ' has-error' : '' }}">
                  <label for="event_date">Tanggal Tiket</label>
                  <input id="event_date" type="date" class="form-control @if ($errors->has('event_date')) is-invalid @endif" name="event_date" tabindex="1" value="{{ $ticket->event_date }}">
                  @if ($errors->has('event_date'))
                    <div class="invalid-feedback">
                      {{ $errors->first('event_date') }}
                    </div>
                  @endif
                </div>
              </div>

              <div class="form-group {{ $errors->has('video_url') ? ' has-error' : '' }}">
                <label for="video_url" class="d-block">Youtube Video Url</label>
                <input id="video_url" type="text" class="form-control @if ($errors->has('video_url')) is-invalid @endif" name="video_url" value="{{ $ticket->video_url }}">
                @if ($errors->has('video_url'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('video_url') }}</strong>
                  </div>
                @endif
              </div>              

              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                  Simpan
                </button>
              </div>
              
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Image / Marker</h6>
            </div>
            <div class="card-body">
              <div class="form-group">
                <div class="text-center">
                  @if (is_null($ticket->image))
                    <img src="{{ asset('assets/stisla/img/news/img02.jpg') }}" class="rounded" id="image-prev" width="200" alt="avatar">
                  @else
                    <img alt="image" src="{{asset('uploads/images/tickets/'.$ticket->image)}}" class="rounded" id="image-prev" width="200" alt="images">
                  @endif
                </div>
              </div>
              <div class="form-group custom-file mb-3 {{ $errors->has('image') ? ' has-error' : '' }}">
                <input id="image" type="file" class="custom-file-input @if ($errors->has('image')) is-invalid @endif" name="image" />
                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                @if ($errors->has('image'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('image') }}</strong>
                  </div>
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })

    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#image-prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
      }
    }

    $("#image").change(function() {
      readURL(this);
    });
  </script>
@endsection