routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Frontend\PageController@landing')->name('landing');
Route::get('/about', 'Frontend\PageController@pageAbout')->name('page.about');
// Route::get('/smart-rec', 'Frontend\SmartController@index')->name('smart-rec.index');
// //Route::post('/smart-rec', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::get('/smart-rec/process', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::post('/package/detail', 'Frontend\SmartController@detailPackage')->name('pg.detail');
Route::get('/checkout/{id}', 'Frontend\PageController@checkout')->name('page.checkout')->middleware('auth');
Route::post('/checkout', 'Frontend\PageController@checkoutStore')->name('page.checkout.store')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/account/profile', 'ProfileController@show')->name('profile.show');
Route::put('/account/profile', 'ProfileController@update')->name('profile.update');
Route::put('/account/profile/member', 'ProfileController@updateMember')->name('profile.update.member');

Route::group(['prefix' => 'main', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('user', 'Backend\UserController@index' )->name('user.index');
    Route::post('user', 'Backend\UserController@store' )->name('user.store');
    Route::get('user/create', 'Backend\UserController@create' )->name('user.create');
    Route::get('user/{id}/edit', 'Backend\UserController@edit' )->name('user.edit');
    Route::put('user/{id}/update', 'Backend\UserController@update' )->name('user.update');
    Route::delete('user/{id}', 'Backend\UserController@destroy' )->name('user.destroy');

    Route::resource('ticket', 'Backend\TicketController');
    Route::resource('order', 'Backend\OrderController');
    Route::resource('payment', 'Backend\PaymentController');
});


Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'role:user']], function () {
    Route::get('/my-order/{id}/cancel', 'Frontend\MyOrderController@cancel')->name('my-order.cancel');
    Route::resource('my-order', 'Frontend\MyOrderController');
});

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $appends = ['display_status', 'display_date'];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function order()
    {
        return $this->belongsTo('App\Order', 'order_id');
    }

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->is_paid;

        switch ($status) {
            case 1:
                $result = 'Terverifikasi';
                break;
            case 0:
                $result = 'Menunggu Verifikasi';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }

    public function getDisplayDateAttribute()
    {
        $result = '';

        $raw = $this->created_at;
        if ($raw != null) {
            $result = date_dmy($raw);
        }
        
        return $result;
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Order;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $orders = Order::with('user', 'ticket');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $orders->whereStatus($request->status);
                }
            }

            $orders = $orders->select('orders.*');

            return Datatables::of($orders)
                ->addIndexColumn()
                ->addColumn('action', function ($order) {
                    return view('partials._action', [
                        'model'           => $order,
                        // 'form_url'        => route('order.destroy', $order->id),
                        'edit_url'        => route('order.edit', $order->id),
                        'show_url'        => route('order.show', $order->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.orders.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);

        return view('backend.orders.show')->with(compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);

        return view('backend.orders.edit')->with(compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'status' => 'required|integer',
        ]);

        $order = Order::find($id);
        $order->status = $request->status;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil mengubah order"
        ]);

        return redirect()->route('order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/PaymentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Payment;
use App\Order;


class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $payments = Payment::with('user', 'order');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $payments->whereStatus($request->status);
                }
            }

            $payments = $payments->select('payments.*');

            return Datatables::of($payments)
                ->addIndexColumn()
                ->addColumn('action', function ($payment) {
                    return view('partials._action', [
                        'model'           => $payment,
                        // 'form_url'        => route('payment.destroy', $payment->id),
                        // 'edit_url'        => route('payment.edit', $payment->id),
                        'verif_url'        => route('payment.edit', $payment->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.payments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $payment = Payment::find($id);

        return view('backend.payments.edit')->with(compact('payment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'is_paid' => 'required|integer',
        ]);

        $payment = Payment::find($id);
        $payment->is_paid = $request->is_paid;
        $payment->save();

        $order = Order::find($payment->order_id);
        $order->status = 200;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil melakukan verifikasi"
        ]);

        return redirect()->route('payment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/TicketController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Order;
use App\Ticket;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $tickets = Ticket::query();

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $tickets->whereStatus($request->status);
                }
            }

            $tickets = $tickets->select('tickets.*');

            return Datatables::of($tickets)
                ->addIndexColumn()
                ->addColumn('action', function ($ticket) {
                    return view('partials._action', [
                        'model'           => $ticket,
                        'form_url'        => route('ticket.destroy', $ticket->id),
                        'edit_url'        => route('ticket.edit', $ticket->id),
                        'show_url'        => route('ticket.show', $ticket->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.tickets.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.tickets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'string',
            'event_date' => 'required|date',
            'price' => 'required|integer',
            'image' => 'required|image',
            'video_url' => 'string',
        ]);

        $ticket = new Ticket();
        $ticket->name = $request->name;
        $ticket->description = $request->description;
        $ticket->event_date = $request->event_date;
        $ticket->price = $request->price;
        $ticket->video_url = $request->video_url;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
           
            $ticket->image = $filename;
        }
        $ticket->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Tiket dengtan nama $ticket->name berhasil dibuat"
        ]);

        return redirect()->route('ticket.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket = Ticket::find($id);

        return view('backend.tickets.show')->with(compact('ticket'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::find($id);

        return view('backend.tickets.edit')->with(compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'description' => 'string',
            'event_date' => 'required|date',
            'price' => 'required|integer',
            'image' => 'image',
            'video_url' => 'string',
        ]);

        $ticket = Ticket::find($id);
        $ticket->name = $request->name;
        $ticket->description = $request->description;
        $ticket->event_date = $request->event_date;
        $ticket->price = $request->price;
        $ticket->video_url = $request->video_url;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);

            // delete old image
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets'
                . DIRECTORY_SEPARATOR . $ticket->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
           
            $ticket->image = $filename;
        }
        $ticket->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Tiket dengtan nama $ticket->name berhasil diubah"
        ]);

        return redirect()->route('ticket.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ticket = Ticket::find($id);

        $check = Order::where('ticket_id', $id)->count();

        if ($check > 0) {
            Session::flash("flash_notification", [
                "level" => "warning",
                "message" => "Tidak dapat menghapus tiket ini, karena tiket ini sudah memiliki order. Alternatif anda dapat menonaktifkannya"
            ]);
            return redirect()->back();
        }

        if ($ticket->image) {
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'tickets'
                . DIRECTORY_SEPARATOR . $ticket->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        $ticket->delete();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil menghapus data"
        ]);

        return redirect()->route('ticket.index');
    }
}

resources/views/backend/payments/edit.blade.php
@extends('layouts.main')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/stisla/modules/bootstrap-daterangepicker/daterangepicker.css') }}">
@endsection

@section('content')
  <section class="section">

    <div class="card mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Verifikasi Pembayaran</h6>
      </div>
      <div class="card-body">
        
        <div class="row">
          <div class="col-md-8">
            <div class="card card-primary">
              <div class="card-header">
                Informasi Order - &nbsp <strong>{{ $payment->order->code }}</strong>
              </div>
              <div class="card-body">
                <div>
                  Nama Pembeli<br>
                  <strong>{{ $payment->order->user->name }}</strong>
                </div>
                <hr>
                <div>
                  Tiket <br>
                  <strong>{{ $payment->order->ticket->name }}</strong>
                </div>
                <hr>
                <div>
                  Tanggal Tiket <br>
                  <strong>{{ $payment->order->ticket->event_date }}</strong>
                </div>
                <hr>
                <div>
                  Status Order <br>
                  <span class="badge badge-primary">
                    {{ $payment->order->display_status }}
                  </span>
                </div>
              </div>

            </div>
          </div>
          <div class="col-md-4">
            <div class="card card-primary">
              <div class="card-header">
                Informasi Harga
              </div>
              <div class="card-body">
                <div>
                  Harga Tiket<br>
                  <strong>Rp {{ rupiah($payment->order->ticket->price) }}</strong>
                </div>
                <hr>
                <div>
                  Qty<br>
                  <strong>Rp {{ rupiah($payment->order->quantity) }}</strong>
                </div>
                <hr>
                <div>
                  Total Harga <br>
                  <strong>Rp {{ rupiah($payment->order->total_price) }}</strong>
                </div>
                <hr>
                {{-- <div>
                  Cara Pembayaran <br>
                  <span class="badge badge-primary">
                    <strong>{{ $payment->order->payment_type_name }}</strong>
                  </span>
                </div> 
                <hr> --}}
              </div>
            </div>

          </div>
          <div class="col-md-8">
            <div class="card card-primary">
              <div class="card-header">
                Informasi Pembayaran</strong>
              </div>
              <form method="POST" action="{{ route('payment.update', $payment->order->id) }}" class="card-body">
                @csrf
                @method('PUT')
                <div>
                  Rekening Atas Nama<br>
                  <strong>{{ $payment->account_holder }}</strong>
                </div>
                <hr>
                <div>
                  Jumlah Transfer <br>
                  <strong>{{ $payment->total_price }}</strong>
                </div>
                <hr>
                <div>
                  Tanggal Transfer <br>
                  <strong>{{ $payment->display_date }}</strong>
                </div>
                <hr>
                <div>
                  Status Pembayaran <br>
                  <span class="badge badge-primary">
                    {{ $payment->display_status }}
                  </span>
                </div>
                <hr>
                <div class="form-group {{ $errors->has('is_paid') ? ' has-error' : '' }}" style="display: none;">
                  <label for="is_paid">Verifikasi</label>
                  <select name="is_paid" class="form-control select2">
                    <option value="1">Verifikasi</option>
                  </select>
                  @if ($errors->has('is_paid'))
                    <div class="invalid-feedback">
                      {{ $errors->first('is_paid') }}
                    </div>
                  @endif
                </div>

                <div class="form-group mt-2">
                  <button type="submit" class="btn btn-success btn-block" tabindex="4">
                    Verifikasi
                  </button>
                </div>

              </form>

            </div>
          </div>

          <div class="col-lg-4">
            <div class="card card-primary">
              <div class="card-header py-3">
                <h6 class="m-0">Bukti Pembayaran</h6>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <div class="text-center">
                    @if (is_null($payment->image))
                      <img src="{{ asset('assets/stisla/img/news/img02.jpg') }}" class="rounded" id="image-prev" width="200" alt="avatar">
                    @else
                      <img alt="image" src="{{asset('uploads/images/payments/'.$payment->image)}}" class="rounded" id="image-prev" width="200" alt="images">
                    @endif
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        </div>
            
      </div>
    </div>
  </section>

@endsection

@section('script')
  <script type="text/javascript" src="{{ asset('assets/stisla/modules/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
  <script>
    function numberFormat(x) {
      return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
    }

    function diffDays(start, end) {
      var a = new Date(start),
      b = new Date(end),
      c = 24*60*60*1000,
      diffDays = Math.round(Math.abs((a - b)/(c)));
      return diffDays;
    }

    @if(Session::has('swal_notification.message'))
      var type = "{{ Session::get('swal_notification.level', 'info') }}";
      switch(type){
        case 'success':
          swal(
            'Sukses!',
            '{{ Session::get('swal_notification.message') }}',
            'success'
          );
          break;

        case 'error':
          swal(
            'Gagal!',
            '{{ Session::get('swal_notification.message') }}',
            'error'
          );
          break;
      }
    @endif
  </script>
@endsection

resources/views/backend/payments/index.blade.php
@extends('layouts.main')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Tiket</h1>
    </div>

    <div class="d-sm-flex align-items-center justify-content-start mb-4">
      
      <div class="form-inline ml-auto">
        <label>Filter Status</label>
        <select name="status" class="form-control-sm ml-2">
          <option value="all">Semua</option>
          <option value="100">Aktif</option>
          <option value="10">Nonaktif</option>
        </select>
        <button class="btn btn-sm btn-primary ml-2" id="btn-filter"><i class="fas fa-filter"></i></button>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">

        <!-- Basic Card Example -->
        <div class="card card-primary">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">List Tiket</h6>
          </div>
          <div class="card-body">

          <div class="table-responsive">
            <table class="table table-striped datatable">
              <thead>                                 
                <tr>
                  <th>#</th>
                  <th>Order Code</th>
                  <th>Pembeli</th>
                  <th>Tanggal Transfer</th>
                  <th>Total Transfer</th>
                  <th>Status</th>
                  <th>#</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>

          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('assets/stisla/modules/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('payment.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'order.code', name: 'order.code'},
            {data: 'user.name', name: 'user.name'},
            {data: 'display_date', name: 'display_date'},
            {data: null, name: 'total_price', render: function ( data, type, row ) {
              return 'Rp ' + numberFormat(parseInt(data.total_price));
            }},
            {data: 'display_status', name: 'status'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });

  function numberFormat(x) {
    return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
  }

  const capitalize = (s) => {
    if (typeof s !== 'string') return ''
    return s.charAt(0).toUpperCase() + s.slice(1)
  }
</script>
@endsection