routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Frontend\PageController@landing')->name('landing');
Route::get('/about', 'Frontend\PageController@pageAbout')->name('page.about');
// Route::get('/smart-rec', 'Frontend\SmartController@index')->name('smart-rec.index');
// //Route::post('/smart-rec', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::get('/smart-rec/process', 'Frontend\SmartController@process')->name('smart-rec.process');
// Route::post('/package/detail', 'Frontend\SmartController@detailPackage')->name('pg.detail');
Route::get('/checkout/{id}', 'Frontend\PageController@checkout')->name('page.checkout')->middleware('auth');
Route::post('/checkout', 'Frontend\PageController@checkoutStore')->name('page.checkout.store')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/account/profile', 'ProfileController@show')->name('profile.show');
Route::put('/account/profile', 'ProfileController@update')->name('profile.update');
Route::put('/account/profile/member', 'ProfileController@updateMember')->name('profile.update.member');

Route::group(['prefix' => 'main', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('user', 'Backend\UserController@index' )->name('user.index');
    Route::post('user', 'Backend\UserController@store' )->name('user.store');
    Route::get('user/create', 'Backend\UserController@create' )->name('user.create');
    Route::get('user/{id}/edit', 'Backend\UserController@edit' )->name('user.edit');
    Route::put('user/{id}/update', 'Backend\UserController@update' )->name('user.update');
    Route::delete('user/{id}', 'Backend\UserController@destroy' )->name('user.destroy');

    Route::resource('ticket', 'Backend\TicketController');
    Route::resource('order', 'Backend\OrderController');
    Route::resource('payment', 'Backend\PaymentController');
});


Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'role:user']], function () {
    Route::get('/my-order/{id}/cancel', 'Frontend\MyOrderController@cancel')->name('my-order.cancel');
    Route::resource('my-order', 'Frontend\MyOrderController');
});

app/Http/Controllers/Frontend/MyOrderController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use Session;
use App\Order;
use App\Payment;

class MyOrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $orders = Order::with('user', 'ticket')->where('user_id', auth()->user()->id);

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $orders->whereStatus($request->status);
                }
            }

            $orders = $orders->select('orders.*');

            return Datatables::of($orders)
                ->addIndexColumn()
                ->addColumn('action', function ($order) {
                    return view('partials._action', [
                        'model'           => $order,
                        // 'form_url'        => route('order.destroy', $order->id),
                        // 'edit_url'        => route('order.edit', $order->id),
                        'show_url'        => route('my-order.show', $order->id),
                        'confirm_url'        => route('my-order.edit', $order->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('frontend.my-orders.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);

        return view('frontend.my-orders.show')->with(compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);

        return view('frontend.my-orders.edit')->with(compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'account_holder' => 'required|string|max:255',
            'total_price' => 'required|integer',
            'image' => 'required|image',
        ]);

        $payment = new Payment();
        $payment->order_id = $id;
        $payment->user_id = auth()->user()->id;
        $payment->total_price = $request->total_price;
        $payment->method = 'Transfer Bank BCA';
        $payment->account_holder = $request->account_holder;
        $payment->is_paid = 0;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = uniqid() . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'payments';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);

            // delete old image
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'payments'
                . DIRECTORY_SEPARATOR . $payment->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
           
            $payment->image = $filename;
        }
        $payment->save();

        $order = Order::find($id);
        $order->status = 150;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil melakukan konfirmasi pembayaran!"
        ]);

        return redirect()->route('my-order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\AlternativeCriteria;
use App\Contract;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Order;
use App\Member;
use App\Employee;
use App\Ticket;
use Auth;
use Session;

class PageController extends Controller
{
    public function landing(Request $request)
    {
        $tickets = Ticket::where('status', 100);

        $condition = (env('DB_CONNECTION', 'mysql') == 'pgsql') ? 'ilike' : 'like';

        if ($request->get('q') != null) {
            if ($request->q != 'all') {
                $tickets->where('name', $condition, '%' . $request->q . '%');
            }
        }

        $tickets = $tickets->paginate(8);
        $q = $request->q;

        return view('frontend.pages.landing')->with(compact('tickets', 'q'));
    }

    public function pageAbout()
    {
        return view('frontend.pages.about');
    }

    public function checkout($id)
    {
        $ticket = Ticket::find($id);
        $user = Auth::user();

        if (!$ticket){
            abort(404);
        }

        return view('frontend.pages.checkout')->with(compact('ticket', 'user'));
    }

    public function checkoutStore(Request $request)
    {
        $this->validate($request, [
            'ticket_id' => 'required|integer',
            'quantity' => 'required|integer',
            'total_price' => 'required|integer',
        ]);

        $id = $request->ticket_id;

        $order = new Order();
        $order->code = strtoupper(uniqid());
        $order->user_id = auth()->user()->id;
        $order->ticket_id = $id;
        $order->quantity = $request->quantity;
        $order->total_price = $request->total_price;
        $order->status = 100;
        $order->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Pemesanan tiket berhasil, silahkan lakukan pembayaran dan konfirmasi!"
        ]);

        return redirect()->route('my-order.edit', $order->id);
    }
}

resources/views/frontend/my-orders/edit.blade.php
@extends('layouts.front')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Upload Bukti Pembayaran</h1>
    </div>

    <form method="POST" action="{{ route('my-order.update', $order->id) }}" enctype="multipart/form-data">
      <div class="row">
        <div class="col-lg-8">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Informasi Pembayaran</h6>
            </div>
            <div class="card-body">
              {{ csrf_field() }}
              @method('PUT')

              <div class="alert alert-info alert-has-icon">
                <div class="alert-icon"><i class="fa fa-info"></i></div>
                <div class="alert-body">
                  <div class="alert-title">Transfer</div>
                  <span>Silahkan Transfer ke bank BCA</span> <br>
                  <span>Atas nama : <b>Museum Geologi Bandung </b></span> <br>
                  <span>No. Rek. : <b>900167187615 </b></span> <br>
                </div>
              </div>

              <div class="form-group {{ $errors->has('code') ? ' has-error' : '' }}">
                <label for="code">Order Code / Invoice</label>
                <input id="code" type="text" class="form-control @if ($errors->has('code')) is-invalid @endif" name="code" tabindex="1" value="{{ $order->code }}" readonly>
                {{-- <input id="id" type="hidden" name="order_id" tabindex="1" value="{{ $order->id }}" readonly> --}}
                @if ($errors->has('code'))
                  <div class="invalid-feedback">
                    {{ $errors->first('code') }}
                  </div>
                @endif
              </div>
              <div class="form-group {{ $errors->has('total_price_order') ? ' has-error' : '' }}">
                <label for="total_price_order">Total Order</label>
                <input id="total_price_order" type="text" class="form-control @if ($errors->has('total_price_order')) is-invalid @endif" name="total_price_order" tabindex="1" value="{{ $order->total_price }}" readonly>
                @if ($errors->has('total_price_order'))
                  <div class="invalid-feedback">
                    {{ $errors->first('total_price_order') }}
                  </div>
                @endif
              </div>

              <div class="row">
                <div class="form-group col-12 {{ $errors->has('account_holder') ? ' has-error' : '' }}">
                  <label for="account_holder">Transfer Atas Nama</label>
                  <input id="account_holder" type="text" class="form-control @if ($errors->has('account_holder')) is-invalid @endif" name="account_holder" tabindex="1" value="{{ old('account_holder') }}">
                  @if ($errors->has('name'))
                    <div class="invalid-feedback">
                      {{ $errors->first('account_holder') }}
                    </div>
                  @endif
                </div>
                <div class="form-group col-12 {{ $errors->has('total_price') ? ' has-error' : '' }}">
                  <label for="total_price">Jumlah Transfer</label>
                  <input id="total_price" type="text" class="form-control @if ($errors->has('total_price')) is-invalid @endif" name="total_price" tabindex="1" value="{{ $order->total_price }}">
                  @if ($errors->has('total_price'))
                    <div class="invalid-feedback">
                      {{ $errors->first('total_price') }}
                    </div>
                  @endif
                </div>
              </div>     

              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                  Simpan
                </button>
              </div>
              
            </div>
          </div>
        </div>

        <div class="col-lg-4">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Bukti Pembayaran</h6>
            </div>
            <div class="card-body">
              <div class="form-group">
                <div class="text-center">
                  <img src="{{ asset('assets/stisla/img/news/img02.jpg') }}" class="rounded" id="image-prev" width="200" alt="avatar">
                </div>
              </div>
              <div class="form-group custom-file mb-3 {{ $errors->has('image') ? ' has-error' : '' }}">
                <input id="image" type="file" class="custom-file-input @if ($errors->has('image')) is-invalid @endif" name="image" />
                <label class="custom-file-label" for="customFile">Pilih Gambar</label>
                @if ($errors->has('image'))
                  <div class="invalid-feedback">
                    <strong>{{ $errors->first('image') }}</strong>
                  </div>
                @endif
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })

    function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function(e) {
        $('#image-prev').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]); // convert to base64 string
      }
    }

    $("#image").change(function() {
      readURL(this);
    });
  </script>
@endsection

resources/views/frontend/my-orders/index.blade.php
@extends('layouts.front')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Pesanan Saya</h1>
    </div>

    <div class="d-sm-flex align-items-center justify-content-start mb-4">
      {{-- <strong><i class="fa fa-info-circle"></i> Info :</strong> &nbsp; Proses pembatalan order dan penambahan denda dapat dilakukan di halaman edit. --}}
      <div class="form-inline ml-auto">
        <label>Filter Status</label>
        <select name="status" class="form-control-sm">
          <option value="all">Semua</option>
          <option value="100">Menunggu Pembayaran</option>
          <option value="150">Menunggu Verifikasi Pembayaran</option>
          <option value="200">Selesai</option>
          <option value="10">Order Dibatalkan</option>
        </select>
        <button class="btn btn-sm btn-primary ml-2" id="btn-filter"><i class="fas fa-filter"></i></button>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">

        <!-- Basic Card Example -->
        <div class="card card-primary">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">List Order</h6>
          </div>
          <div class="card-body">

          <div class="table-responsive">
            <table class="table table-striped datatable">
              <thead>                                 
                <tr>
                  <th>#</th>
                  <th>Invoice</th>
                  <th>Nama Pembeli</th>
                  <th>Nama Tiket</th>
                  <th>Harga</th>
                  <th>Qty</th>
                  <th>Total Harga</th>
                  <th>Status</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>

          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('assets/stisla/modules/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('my-order.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'user.name', name: 'user.name'},
            {data: 'ticket.name', name: 'ticket.name'},
            {data: null, name: 'ticket.price', render: function ( data, type, row ) {
              return 'Rp ' + numberFormat(parseInt(data.ticket.price));
            }},
            {data: 'quantity', name: 'quantity'},
            {data: null, name: 'total_price', render: function ( data, type, row ) {
              return 'Rp ' + numberFormat(parseInt(data.total_price));
            }},
            {data: 'display_status', name: 'display_status'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });

  function numberFormat(x) {
    return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
  }

  const capitalize = (s) => {
    if (typeof s !== 'string') return ''
    return s.charAt(0).toUpperCase() + s.slice(1)
  }
</script>
@endsection

resources/views/frontend/my-orders/show.blade.php
@extends('layouts.front')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/stisla/modules/bootstrap-daterangepicker/daterangepicker.css') }}">
@endsection

@section('content')
  <section class="section">

    <div class="card mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Detail Order</h6>
      </div>
      <div class="card-body">
        
        <div class="row">
          <div class="col-md-8">
            <div class="card card-primary">
              <div class="card-header">
                Informasi Order - &nbsp <strong>{{ $order->code }}</strong>
              </div>
              <form method="POST" action="{{ route('my-order.update', $order->id) }}" class="card-body">
                @csrf
                @method('PUT')
                <div>
                  Nama Pembeli<br>
                  <strong>{{ $order->user->name }}</strong>
                </div>
                <hr>
                <div>
                  Tiket <br>
                  <strong>{{ $order->ticket->name }}</strong>
                </div>
                <hr>
                <div>
                  Tanggal Tiket <br>
                  <strong>{{ $order->ticket->event_date }}</strong>
                </div>
                <hr>
                <div>
                  Status Order <br>
                  <span class="badge badge-primary">
                    {{ $order->display_status }}
                  </span>
                </div>
                <hr>
                <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                  <label for="status">Ubah Status</label>
                  <select name="status" class="form-control select2">
                    <option value="100" {{ $order->status == 100 ? 'selected' : '' }}>Menunggu Pembayaran</option>
                    <option value="200" {{ $order->status == 200 ? 'selected' : '' }}>Selesai</option>
                    <option value="10" {{ $order->status == 10 ? 'selected' : '' }}>Dibatalkan</option>
                  </select>
                  @if ($errors->has('status'))
                    <div class="invalid-feedback">
                      {{ $errors->first('status') }}
                    </div>
                  @endif
                </div>

              </form>

            </div>
          </div>
          <div class="col-md-4">
            <div class="card card-primary">
              <div class="card-header">
                Informasi Harga
              </div>
              <div class="card-body">
                <div>
                  Harga Tiket<br>
                  <strong>Rp {{ rupiah($order->ticket->price) }}</strong>
                </div>
                <hr>
                <div>
                  Qty<br>
                  <strong>Rp {{ rupiah($order->quantity) }}</strong>
                </div>
                <hr>
                <div>
                  Total Harga <br>
                  <strong>Rp {{ rupiah($order->total_price) }}</strong>
                </div>
                <hr>
                {{-- <div>
                  Cara Pembayaran <br>
                  <span class="badge badge-primary">
                    <strong>{{ $order->payment_type_name }}</strong>
                  </span>
                </div> 
                <hr> --}}
              </div>
            </div>

          </div>

          <div class="col-md-12">
            <div class="card card-primary">
              <div class="card-header">
                Histori Pembayaran
              </div>
              <div class="card-body p-0">
                <table class="table table-striped table-md">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Metode Bayar</th>
                      <th>Transfer Atas Nama</th>
                      <th>Jumlah Ditransfer</th>
                      <th>Tanggal Transfer</th>
                      <th>Bukti Pembayaran</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($order->payments as $key => $item)    
                      <tr>
                        <td>{{ ++$key }}</td>
                        <td>{{ $item->method }}</td>
                        <td>{{ $item->account_holder }}</td>
                        <td>Rp {{ rupiah($item->total_price) }}</td>
                        <td>{{ date_dmy($item->created_at) }}</td>
                        <td><img class="mr-3 rounded" width="80" src="{{asset('uploads/images/payments/'.$item->image)}}" alt="img"></td>
                        <td><div class="badge badge-info">{{ $item->display_status }}</div></td>
                      </tr>
                    @empty
                      <tr><td colspan="7" class="text-center">Belum Ada Pembayaran</td></tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
            
      </div>
    </div>
  </section>

@endsection

@section('script')
  <script type="text/javascript" src="{{ asset('assets/stisla/modules/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
  <script>
    function numberFormat(x) {
      return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
    }

    function diffDays(start, end) {
      var a = new Date(start),
      b = new Date(end),
      c = 24*60*60*1000,
      diffDays = Math.round(Math.abs((a - b)/(c)));
      return diffDays;
    }

    @if(Session::has('swal_notification.message'))
      var type = "{{ Session::get('swal_notification.level', 'info') }}";
      switch(type){
        case 'success':
          swal(
            'Sukses!',
            '{{ Session::get('swal_notification.message') }}',
            'success'
          );
          break;

        case 'error':
          swal(
            'Gagal!',
            '{{ Session::get('swal_notification.message') }}',
            'error'
          );
          break;
      }
    @endif
  </script>
@endsection